name: Vuca
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  http: ^1.3.0
  logger: ^2.5.0
  video_player: ^2.7.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_nav_bar: ^5.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/web/vinheta.gif
    - assets/web/vinheta.mp4
    - assets/txt_logo.png
    - assets/grp_returner.svg
    - assets/img_perfil.svg
    - assets/ver_perfil.svg
    - assets/img_alterar_senha.svg
    - assets/img_email.svg
    - assets/img_excluir.svg
    - assets/img_sair.svg
    - assets/img_configuracoes.svg
    - assets/txt_logo.svg
    - assets/cruzamento.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf

